const countryRules = {
  India: {
    name: "India",
    states: [
      { name: "Andhra Pradesh", code: "28", gstStateCode: "37" },
      { name: "Arunachal Pradesh", code: "12", gstStateCode: "12" },
      { name: "Assam", code: "18", gstStateCode: "18" },
      { name: "Bihar", code: "10", gstStateCode: "10" },
      { name: "Chhattisgarh", code: "22", gstStateCode: "22" },
      { name: "Goa", code: "30", gstStateCode: "30" },
      { name: "Gujarat", code: "24", gstStateCode: "24" },
      { name: "Haryana", code: "06", gstStateCode: "06" },
      { name: "Himachal Pradesh", code: "02", gstStateCode: "02" },
      { name: "Jharkhand", code: "20", gstStateCode: "20" },
      { name: "Karnataka", code: "29", gstStateCode: "29" },
      { name: "Kerala", code: "32", gstStateCode: "32" },
      { name: "Madhya Pradesh", code: "23", gstStateCode: "23" },
      { name: "Maharashtra", code: "27", gstStateCode: "27" },
      { name: "Manipur", code: "14", gstStateCode: "14" },
      { name: "Meghalaya", code: "17", gstStateCode: "17" },
      { name: "Mizoram", code: "15", gstStateCode: "15" },
      { name: "Nagaland", code: "13", gstStateCode: "13" },
      { name: "Odisha", code: "21", gstStateCode: "21" },
      { name: "Punjab", code: "03", gstStateCode: "03" },
      { name: "Rajasthan", code: "08", gstStateCode: "08" },
      { name: "Sikkim", code: "11", gstStateCode: "11" },
      { name: "Tamil Nadu", code: "33", gstStateCode: "33" },
      { name: "Telangana", code: "36", gstStateCode: "36" },
      { name: "Tripura", code: "16", gstStateCode: "16" },
      { name: "Uttar Pradesh", code: "09", gstStateCode: "09" },
      { name: "Uttarakhand", code: "05", gstStateCode: "05" },
      { name: "West Bengal", code: "19", gstStateCode: "19" },
      // Union Territories
      { name: "Andaman and Nicobar Islands", code: "35", gstStateCode: "35" },
      { name: "Chandigarh", code: "04", gstStateCode: "04" },
      { name: "Dadra and Nagar Haveli and Daman & Diu", code: "26", gstStateCode: "26" },
      { name: "Delhi", code: "07", gstStateCode: "07" },
      { name: "Jammu and Kashmir", code: "01", gstStateCode: "01" },
      { name: "Ladakh", code: "38", gstStateCode: "38" },
      { name: "Lakshadweep", code: "31", gstStateCode: "31" },
      { name: "Puducherry", code: "34", gstStateCode: "34" },
    ],
    postalCodeRegex: /^\d{6}$/,
    postalCodeLabel: "PIN Code",
    postalCodeMessage: "PIN code must be 6 digits",
    taxFields: ["PAN", "GST"],
    taxIdentifiers: [
      { value: "PAN", label: "PAN (India)" },
      { value: "GST", label: "GSTIN (India)" },
    ],
    idProofs: ["PAN", "Aadhaar", "Passport", "Driving Licence", "Voter ID", "Ration Card"],
    currency: "INR",
    currencySymbol: "₹",
  },

  USA: {
    name: "USA",
    states: [
      { name: "Alabama", code: "AL" },
      { name: "Alaska", code: "AK" },
      { name: "Arizona", code: "AZ" },
      { name: "Arkansas", code: "AR" },
      { name: "California", code: "CA" },
      { name: "Colorado", code: "CO" },
      { name: "Connecticut", code: "CT" },
      { name: "Delaware", code: "DE" },
      { name: "Florida", code: "FL" },
      { name: "Georgia", code: "GA" },
      { name: "Hawaii", code: "HI" },
      { name: "Idaho", code: "ID" },
      { name: "Illinois", code: "IL" },
      { name: "Indiana", code: "IN" },
      { name: "Iowa", code: "IA" },
      { name: "Kansas", code: "KS" },
      { name: "Kentucky", code: "KY" },
      { name: "Louisiana", code: "LA" },
      { name: "Maine", code: "ME" },
      { name: "Maryland", code: "MD" },
      { name: "Massachusetts", code: "MA" },
      { name: "Michigan", code: "MI" },
      { name: "Minnesota", code: "MN" },
      { name: "Mississippi", code: "MS" },
      { name: "Missouri", code: "MO" },
      { name: "Montana", code: "MT" },
      { name: "Nebraska", code: "NE" },
      { name: "Nevada", code: "NV" },
      { name: "New Hampshire", code: "NH" },
      { name: "New Jersey", code: "NJ" },
      { name: "New Mexico", code: "NM" },
      { name: "New York", code: "NY" },
      { name: "North Carolina", code: "NC" },
      { name: "North Dakota", code: "ND" },
      { name: "Ohio", code: "OH" },
      { name: "Oklahoma", code: "OK" },
      { name: "Oregon", code: "OR" },
      { name: "Pennsylvania", code: "PA" },
      { name: "Rhode Island", code: "RI" },
      { name: "South Carolina", code: "SC" },
      { name: "South Dakota", code: "SD" },
      { name: "Tennessee", code: "TN" },
      { name: "Texas", code: "TX" },
      { name: "Utah", code: "UT" },
      { name: "Vermont", code: "VT" },
      { name: "Virginia", code: "VA" },
      { name: "Washington", code: "WA" },
      { name: "West Virginia", code: "WV" },
      { name: "Wisconsin", code: "WI" },
      { name: "Wyoming", code: "WY" },
      { name: "District of Columbia", code: "DC" },
    ],
    postalCodeRegex: /^\d{5}(-\d{4})?$/,
    postalCodeLabel: "ZIP Code",
    postalCodeMessage: "ZIP code must be 5 digits (e.g. 10001)",
    taxFields: ["EIN", "SSN"],
    taxIdentifiers: [
      { value: "EIN", label: "EIN (USA)" },
      { value: "SSN", label: "SSN (USA)" },
    ],
    idProofs: ["SSN", "Passport", "Driver License", "State ID"],
    currency: "USD",
    currencySymbol: "$",
  },

  UK: {
    name: "UK",
    states: [
      { name: "England", code: "ENG" },
      { name: "Scotland", code: "SCT" },
      { name: "Wales", code: "WLS" },
      { name: "Northern Ireland", code: "NIR" },
      { name: "London", code: "LON" },
      { name: "Greater Manchester", code: "GM" },
      { name: "West Midlands", code: "WM" },
      { name: "West Yorkshire", code: "WY" },
      { name: "Hampshire", code: "HAM" },
      { name: "Essex", code: "ESS" },
      { name: "Kent", code: "KEN" },
      { name: "Surrey", code: "SRY" },
    ],
    postalCodeRegex: /^[A-Z]{1,2}\d[A-Z\d]? ?\d[A-Z]{2}$/i,
    postalCodeLabel: "Postcode",
    postalCodeMessage: "Enter a valid UK postcode (e.g. SW1A 1AA)",
    taxFields: ["VAT", "CompanyNumber"],
    taxIdentifiers: [
      { value: "VAT", label: "VAT (UK)" },
      { value: "CompanyNumber", label: "Company Number (UK)" },
    ],
    idProofs: ["Passport", "Driving Licence", "National Insurance"],
    currency: "GBP",
    currencySymbol: "£",
  },

  SaudiArabia: {
    name: "Saudi Arabia",
    states: [
      { name: "Riyadh", code: "01" },
      { name: "Makkah", code: "02" },
      { name: "Madinah", code: "03" },
      { name: "Qassim", code: "04" },
      { name: "Eastern Province", code: "05" },
      { name: "Asir", code: "06" },
      { name: "Tabuk", code: "07" },
      { name: "Hail", code: "08" },
      { name: "Northern Borders", code: "09" },
      { name: "Jazan", code: "10" },
      { name: "Najran", code: "11" },
      { name: "Al-Bahah", code: "12" },
      { name: "Al-Jouf", code: "13" },
      { name: "Jeddah", code: "14" },
    ],
    postalCodeRegex: /^\d{5}$/,
    postalCodeLabel: "Postal Code",
    postalCodeMessage: "Postal code must be 5 digits",
    taxFields: ["VAT", "NationalID"],
    taxIdentifiers: [
      { value: "VAT", label: "VAT (KSA)" },
      { value: "NationalID", label: "National ID / Iqama" },
    ],
    idProofs: ["Iqama", "National ID", "Passport"],
    currency: "SAR",
    currencySymbol: "﷼",
  },

  UAE: {
    name: "UAE",
    states: [
      { name: "Abu Dhabi", code: "AZ" },
      { name: "Dubai", code: "DU" },
      { name: "Sharjah", code: "SH" },
      { name: "Ajman", code: "AJ" },
      { name: "Umm Al Quwain", code: "UQ" },
      { name: "Ras Al Khaimah", code: "RK" },
      { name: "Fujairah", code: "FU" },
    ],
    postalCodeRegex: /.*/,
    postalCodeLabel: "P.O. Box",
    postalCodeMessage: "Enter PO Box number (optional)",
    taxFields: ["VAT", "TRN"],
    taxIdentifiers: [
      { value: "VAT", label: "VAT (UAE)" },
      { value: "TRN", label: "Tax Registration Number (TRN)" },
    ],
    idProofs: ["Emirates ID", "Passport", "Visa"],
    currency: "AED",
    currencySymbol: "د.إ",
  },

  Canada: {
    name: "Canada",
    states: [
      { name: "Alberta", code: "AB" },
      { name: "British Columbia", code: "BC" },
      { name: "Manitoba", code: "MB" },
      { name: "New Brunswick", code: "NB" },
      { name: "Newfoundland and Labrador", code: "NL" },
      { name: "Northwest Territories", code: "NT" },
      { name: "Nova Scotia", code: "NS" },
      { name: "Nunavut", code: "NU" },
      { name: "Ontario", code: "ON" },
      { name: "Prince Edward Island", code: "PE" },
      { name: "Quebec", code: "QC" },
      { name: "Saskatchewan", code: "SK" },
      { name: "Yukon", code: "YT" },
    ],
    postalCodeRegex: /^[A-Za-z]\d[A-Za-z] ?\d[A-Za-z]\d$/,
    postalCodeLabel: "Postal Code",
    postalCodeMessage: "Enter a valid Canadian postal code (e.g. A1A 1A1)",
    taxFields: ["GST_HST", "BN"],
    taxIdentifiers: [
      { value: "GST_HST", label: "GST/HST Number (Canada)" },
      { value: "BN", label: "Business Number (BN)" },
    ],
    idProofs: ["SIN", "Passport", "Driver License"],
    currency: "CAD",
    currencySymbol: "$",
  },

  Australia: {
    name: "Australia",
    states: [
      { name: "New South Wales", code: "NSW" },
      { name: "Victoria", code: "VIC" },
      { name: "Queensland", code: "QLD" },
      { name: "Western Australia", code: "WA" },
      { name: "South Australia", code: "SA" },
      { name: "Tasmania", code: "TAS" },
      { name: "Australian Capital Territory", code: "ACT" },
      { name: "Northern Territory", code: "NT" },
    ],
    postalCodeRegex: /^\d{4}$/,
    postalCodeLabel: "Postcode",
    postalCodeMessage: "Postcode must be 4 digits",
    taxFields: ["ABN", "ACN"],
    taxIdentifiers: [
      { value: "ABN", label: "ABN (Australia)" },
      { value: "ACN", label: "ACN (Australia)" },
    ],
    idProofs: ["Passport", "Driver Licence", "Medicare Card"],
    currency: "AUD",
    currencySymbol: "$",
  },

  Germany: {
    name: "Germany",
    states: [
      { name: "Baden-Württemberg", code: "BW" },
      { name: "Bavaria", code: "BY" },
      { name: "Berlin", code: "BE" },
      { name: "Brandenburg", code: "BB" },
      { name: "Bremen", code: "HB" },
      { name: "Hamburg", code: "HH" },
      { name: "Hesse", code: "HE" },
      { name: "Lower Saxony", code: "NI" },
      { name: "Mecklenburg-Vorpommern", code: "MV" },
      { name: "North Rhine-Westphalia", code: "NW" },
      { name: "Rhineland-Palatinate", code: "RP" },
      { name: "Saarland", code: "SL" },
      { name: "Saxony", code: "SN" },
      { name: "Saxony-Anhalt", code: "ST" },
      { name: "Schleswig-Holstein", code: "SH" },
      { name: "Thuringia", code: "TH" },
    ],
    postalCodeRegex: /^\d{5}$/,
    postalCodeLabel: "Postleitzahl (PLZ)",
    postalCodeMessage: "Postal code must be 5 digits",
    taxFields: ["VAT", "Steuernummer"],
    taxIdentifiers: [
      { value: "VAT", label: "USt-IdNr (VAT)" },
      { value: "Steuernummer", label: "Steuernummer" },
    ],
    idProofs: ["Passport", "Personalausweis"],
    currency: "EUR",
    currencySymbol: "€",
  },

  France: {
    name: "France",
    states: [
      { name: "Auvergne-Rhône-Alpes", code: "ARA" },
      { name: "Bourgogne-Franche-Comté", code: "BFC" },
      { name: "Brittany", code: "BRE" },
      { name: "Centre-Val de Loire", code: "CVL" },
      { name: "Corsica", code: "COR" },
      { name: "Grand Est", code: "GES" },
      { name: "Hauts-de-France", code: "HDF" },
      { name: "Île-de-France", code: "IDF" },
      { name: "Normandy", code: "NOR" },
      { name: "Nouvelle-Aquitaine", code: "NAQ" },
      { name: "Occitanie", code: "OCC" },
      { name: "Pays de la Loire", code: "PDL" },
      { name: "Provence-Alpes-Côte d'Azur", code: "PAC" },
    ],
    postalCodeRegex: /^\d{5}$/,
    postalCodeLabel: "Code Postal",
    postalCodeMessage: "Postal code must be 5 digits",
    taxFields: ["VAT", "SIREN"],
    taxIdentifiers: [
      { value: "VAT", label: "Numéro de TVA" },
      { value: "SIREN", label: "SIREN / SIRET" },
    ],
    idProofs: ["Passport", "Carte Nationale d'Identité"],
    currency: "EUR",
    currencySymbol: "€",
  },

  Singapore: {
    name: "Singapore",
    states: [
      { name: "Central Region", code: "CR" },
      { name: "East Region", code: "ER" },
      { name: "North Region", code: "NR" },
      { name: "North-East Region", code: "NER" },
      { name: "West Region", code: "WR" },
    ],
    postalCodeRegex: /^\d{6}$/,
    postalCodeLabel: "Postal Code",
    postalCodeMessage: "Postal code must be 6 digits",
    taxFields: ["GST", "UEN"],
    taxIdentifiers: [
      { value: "GST", label: "GST Registration (Singapore)" },
      { value: "UEN", label: "UEN (Unique Entity Number)" },
    ],
    idProofs: ["NRIC", "Passport", "Employment Pass"],
    currency: "SGD",
    currencySymbol: "$",
  },

  Bhutan: {
    name: "Bhutan",
    states: [
      { name: "Thimphu", code: "TH" },
      { name: "Paro", code: "PA" },
      { name: "Punakha", code: "PU" },
      { name: "Wangdue Phodrang", code: "WP" },
      { name: "Bumthang", code: "BU" },
      { name: "Trashigang", code: "TG" },
      { name: "Mongar", code: "MO" },
      { name: "Trongsa", code: "TR" },
      { name: "Sarpang", code: "SA" },
      { name: "Samtse", code: "SM" },
    ],
    postalCodeRegex: /^\d{3,5}$/,
    postalCodeLabel: "Postal Code",
    postalCodeMessage: "Enter a valid Bhutan postal code (3–5 digits)",
    taxFields: ["TIN"],
    taxIdentifiers: [{ value: "TIN", label: "TIN (Bhutan)" }],
    idProofs: ["Passport", "National ID", "Citizenship ID"],
    currency: "BTN",
    currencySymbol: "Nu",
  },

  Nepal: {
    name: "Nepal",
    states: [
      { name: "Bagmati Province", code: "BAG" },
      { name: "Gandaki Province", code: "GAN" },
      { name: "Lumbini Province", code: "LUM" },
      { name: "Karnali Province", code: "KAR" },
      { name: "Sudurpashchim Province", code: "SUD" },
      { name: "Madhesh Province", code: "MAD" },
      { name: "Koshi Province", code: "KOS" },
    ],
    postalCodeRegex: /^\d{5}$/,
    postalCodeLabel: "Postal Code",
    postalCodeMessage: "Postal code must be 5 digits",
    taxFields: ["PAN", "VAT"],
    taxIdentifiers: [
      { value: "PAN", label: "PAN (Nepal)" },
      { value: "VAT", label: "VAT Registration (Nepal)" },
    ],
    idProofs: ["Citizenship Card", "Passport", "Driving Licence"],
    currency: "NPR",
    currencySymbol: "Rs",
  },

  Japan: {
    name: "Japan",
    states: [
      { name: "Tokyo", code: "TK" },
      { name: "Osaka", code: "OS" },
      { name: "Kanagawa", code: "KN" },
      { name: "Aichi", code: "AC" },
      { name: "Saitama", code: "ST" },
      { name: "Chiba", code: "CH" },
      { name: "Hyogo", code: "HY" },
      { name: "Hokkaido", code: "HK" },
      { name: "Fukuoka", code: "FK" },
      { name: "Kyoto", code: "KY" },
    ],
    postalCodeRegex: /^\d{3}-?\d{4}$/,
    postalCodeLabel: "Postal Code (〒)",
    postalCodeMessage: "Postal code must be in format 123-4567",
    taxFields: ["CorporateNumber", "ConsumptionTax"],
    taxIdentifiers: [
      { value: "CorporateNumber", label: "Corporate Number (法人番号)" },
      { value: "ConsumptionTax", label: "Consumption Tax Registration" },
    ],
    idProofs: ["My Number Card", "Passport", "Residence Card"],
    currency: "JPY",
    currencySymbol: "¥",
  },

  default: {
    name: "Default",
    states: [],
    postalCodeRegex: /.+/,
    postalCodeLabel: "Postal Code",
    postalCodeMessage: "Enter postal/zip code",
    taxFields: [],
    taxIdentifiers: [],
    idProofs: [],
    currency: "",
    currencySymbol: "",
  },
};

export default countryRules;